version: '3.8'

services:
  subelmysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=T0r0m0ch023$
    ports:
      - '3306:3306'
    volumes:
      - ./subelmysql/:/var/lib/mysql

volumes:
  subelmysql:
    driver: local
