version: '3.8'
services:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=subeladmin
      - GF_SECURITY_ADMIN_PASSWORD=T0r0m0ch023$
    volumes:
      - grafanavol:/var/lib/grafana

volumes:
  grafanavol:
